In [2]:
import numpy as np

In [3]:
x = np.arange(16.0).reshape(4, 4)

In [4]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [5]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [6]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

In [7]:
x = np.arange(8.0).reshape(2, 2, 2)

In [8]:
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [9]:
np.vsplit(x, 2)

[array([[[0., 1.],
         [2., 3.]]]),
 array([[[4., 5.],
         [6., 7.]]])]